---
title: "phyloseq_tutorial"
output: html_document
date: "2024-03-07"
---

```{r phyloseq setup}
library(phyloseq); packageVersion("phyloseq")
library(Biostrings); packageVersion("Biostrings")
library(ggplot2); packageVersion("ggplot2")
library(tidyverse)
library(here)
library(dplyr)

# Set plot theme to a simple black-and-white design
theme_set(theme_bw())
```

```{r phyloseq preprocessing}
# Import your output ASV table from DADA2 (wide format).
asvs <- read.csv(here("data", "sequencing_data", "Baja_MiFish_ASVs_wide.csv"),row.names=1)

# Import your taxonomy table and hash key. We will merge these two files to generate a taxonomy table formatted for phyloseq.
tax <- read.csv (here("data", "sequencing_data", "Baja_MiFish_taxa_table.csv"))
hash <- read.csv(here("data", "sequencing_data","Baja_MiFish_hash_key.csv"))

# Import the metadata file. Before importing, make sure the order of your samples in the ASV table matches the order in the metadata table. You can check this in Excel before importing or you can filter tables and edit row names in R, whichever you prefer. I will provide an example of how to do it in R.
metadata <- read.csv(here("data", "baja_edna_metadata.csv"), row.names=1)
```

```{r phyloseq format}
# Format the ASV and tax tables for phyloseq

# In this case each ASV (taxon) is a row
ASV = otu_table(asvs, taxa_are_rows=TRUE)

# For phyloseq taxonomy, we need to merge the tax and hash tables so that we have a list of hashes with associated taxonomy. 

# Now we can merge on the 'Sequence' column and then drop it from the merged data frame
tax_ps <- left_join(hash, tax, by='Sequence')
tax_ps <- select(tax_ps, -Sequence)

# Convert the hashes to row names and convert the whole data frame to a matrix
rownames(tax_ps) <- tax_ps$Hash
tax_ps <- select(tax_ps, -Hash)
tax_ps_mat <- as.matrix(tax_ps)

# Convert the taxonmy table into phyloseq format
TAX <- tax_table(tax_ps_mat)
```

```{r metadata}
# The Baja metadata row names are the same as the ASV table column names, so we don't need to do any name editing!

# If you removed any samples during DADA2 processing, they need to be removed from the metatdata file too

# Check the number of samples in the ASV table
length(colnames(asvs))

# Check the number of samples in the metadata table
length(rownames(metadata))

# They are the same! You can take a closer look at the actual names and make sure they are identical if you're concerned, otherwise move on to the next step (line 78).

# # IF THE TWO NUMBERS ABOVE ARE DIFFERENT:  Let's make a list of the names we want to keep
# samples.to.keep <- colnames(asvs)
# 
# metadata.filt <-filter(metadata, row.names(metadata) %in%
#                                      samples.to.keep)
# 
# # Check again that the number of metadata rows matches the number of ASV table columns
# length(colnames(asvs))
# length(rownames(metadata.filt))

# Convert the metadata table into phyloseq format (use "metadata.filt" instead of "metadata" if you filtered out metadata rows)
MET <- sample_data(metadata)

# Make the phyloseq object from the ASV table, taxonomy table, and metadata table
ps <- phyloseq(ASV, MET, TAX)
```

```{r phyloseq prep}
# Transform data to proportions as appropriate for Bray-Curtis distances
ps.prop <- transform_sample_counts(ps, function(otu) otu/sum(otu))

# The sample_data has sample names as rownames, but we can add a column with the names as well
sample_data(ps.prop)['sample.id'] <-
  row.names(sample_data(ps.prop))
```
Now we can run some basic diversity analyses on both data sets (with and without control samples)

```{r phyloseq alpha diversity}
# Plot alpha diversity metrics
plot_richness(ps.prop, x="lat_group", measures=c("Shannon", "Simpson"), color="lat_group")
```

```{r phyloseq beta diversity}
# Plot beta diversity in NMDS

# Generate the ordinations using the Bray-Curtis distance metric
ord.nmds.bray <- ordinate(ps.prop, "NMDS", "bray")

# Plot!

# With controls
p1 <- plot_ordination(ps.prop, ord.nmds.bray, 
                      color="lat_group", 
                      title="Bray NMDS",
                      label="sample.id")
p1

# Looks like BAJA_23 sample is a real outlier! Let's see if we can figure out why
# To explore the phyloseq we can convert the object components to data frames
asv <- data.frame(otu_table(ps.prop))
tax <- data.frame(tax_table(ps.prop))
sd <- data.frame(sample_data(ps.prop))

# Using the "ASV" data frame let's look at FISH_125
BAJA_23 <- subset(asv, ,"BAJA_23")

# All (100%) of the ASVs belong to the ASV with the hash "64c44b52d311c1326676036ca71567384afb01a8". What is the taxonomy of that ASV?

tax_hash <- tax_ps %>% 
  filter(row.names(tax_ps) %in%
           "64c44b52d311c1326676036ca71567384afb01a8")

# It is annotated as "Homo sapiens" :(

# Filter this sample and re-run the analyses as before. How do the alpha and beta diversity charts look now?

# Remove outlier sample
outlier <- c("BAJA_23")
ps.prop.pruned <- prune_samples(sample_names(ps.prop) !=
                                  outlier, ps.prop)

# New NMDS and plot
ord.nmds.bray.pruned <- ordinate(ps.prop.pruned,
                                    "NMDS", "bray")

p3 <- plot_ordination(ps.prop.pruned, 
                      ord.nmds.bray.pruned, 
                      color="lat_group", 
                      title="Bray NMDS") +
  theme_classic()
p3

# You can find more examples of ordination in phyloseq here: https://joey711.github.io/phyloseq/plot_ordination-examples.html
```

```{r phyloseq bar plots}
top20 <- names(sort(taxa_sums(ps.prop.pruned),
                    decreasing=TRUE))[1:20]
#ps.top20 <- transform_sample_counts(ps, function(OTU) OTU/sum(OTU))
ps.top20 <- prune_taxa(top20, ps.prop.pruned)
bar1 <- plot_bar(ps.top20, x="Site_ID", fill="Family") +
  facet_wrap(~lat_group, scales="free_x")

# Uh oh, looks like we have some non-fish families in here! Try to filter out these taxa and re-run the analyses. You may have to re-filter samples as well.
```
```{r phyloseq filtertax}
# Let's filter out the two obvious contaminant families
# I can't find a way to do this in one step, bonus points if you can!
ps.prop.pruned.v2 <- subset_taxa(ps.prop.pruned,
                                Family != "Bovidae")
ps.prop.pruned.v2 <- subset_taxa(ps.prop.pruned.v2,
                                Family != "Hominidae")

top20 <- names(sort(taxa_sums(ps.prop.pruned.v2),
                    decreasing=TRUE))[1:20]
ps.top20 <- prune_taxa(top20, ps.prop.pruned.v2)
bar2 <- plot_bar(ps.top20, x="Site_ID", fill="Family") +
  facet_wrap(~lat_group, scales="free_x")

bar2
```